// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.OAuth.Database;

#nullable disable

namespace ConfPlan.Api.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20250716151140_UpdateSeedingData")]
    partial class UpdateSeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConfPlan.Shared.Conference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdRoom")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSpeaker")
                        .HasColumnType("uuid");

                    b.Property<int>("Participant")
                        .HasColumnType("integer");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdRoom");

                    b.HasIndex("IdSpeaker");

                    b.ToTable("Conferences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c21926cc-f0bb-4a65-9ac4-9f4e2ed70530"),
                            Day = "Jour 1",
                            Description = "Une plongée dans les dernières avancées du machine learning et leur application dans les systèmes intelligents. Michel Dupont abordera les enjeux pédagogiques et industriels de l’intelligence artificielle au service de l’innovation.\n\n",
                            IdRoom = new Guid("23e25c37-1d79-45f2-b0d5-8f7f4144525c"),
                            IdSpeaker = new Guid("aac7801e-83fc-4f45-89a1-9f867a1efc90"),
                            Participant = 2,
                            TimeSlot = "9h30 - 10h",
                            Title = "Apprentissage Automatique et Transformation Numérique"
                        },
                        new
                        {
                            Id = new Guid("c61f352f-95be-4c41-948a-2cb77a77de1b"),
                            Day = "Jour 2",
                            Description = "Découvrez comment allier esthétique, performance et responsabilité dans la conception d’interfaces. Victoria Martin partage son approche du design émotionnel et de l’accessibilité, illustrée par des cas concrets et des pratiques exemplaires du secteur.\n\n",
                            IdRoom = new Guid("16d87d5d-6c25-448c-9bb9-65b0a7c2e729"),
                            IdSpeaker = new Guid("3e499e2f-1db7-4aa9-b3ab-810b5cb7e5b1"),
                            Participant = 5,
                            TimeSlot = "10h30 - 11h",
                            Title = "Design Éthique et UX : Créer des Interfaces Responsables\n"
                        },
                        new
                        {
                            Id = new Guid("18717e1e-cc3c-4e54-8a89-91c40b27f0a5"),
                            Day = "Jour 3",
                            Description = "Albert MetalStein explore les innovations dans le domaine des matériaux métalliques. Il présentera des recherches sur la conductivité, la résistance et les structures quantiques, avec un regard vulgarisé et passionné sur les défis de l’ingénierie moderne.\n\n",
                            IdRoom = new Guid("5bcbef3c-9790-4032-84c2-3b0706464b6f"),
                            IdSpeaker = new Guid("f777e354-cb8c-438c-b15e-5d6ad3eb71e6"),
                            Participant = 15,
                            TimeSlot = "11h - 12h",
                            Title = "Métaux du Futur : Science, Innovation et Applications"
                        });
                });

            modelBuilder.Entity("ConfPlan.Shared.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a738c4e-9c30-48d2-9817-f59a657e529c"),
                            RoleName = "Visiteur"
                        },
                        new
                        {
                            Id = new Guid("d5ab69c2-4b14-4a15-8a90-1b3a86eb8aa2"),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("a3fef80b-2b2e-46d1-a88e-123d0d7a7615"),
                            RoleName = "Sponsor"
                        });
                });

            modelBuilder.Entity("ConfPlan.Shared.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23e25c37-1d79-45f2-b0d5-8f7f4144525c"),
                            CurrentCapacity = 0,
                            MaxCapacity = 20,
                            Name = "Salle A"
                        },
                        new
                        {
                            Id = new Guid("16d87d5d-6c25-448c-9bb9-65b0a7c2e729"),
                            CurrentCapacity = 0,
                            MaxCapacity = 20,
                            Name = "Salle B"
                        },
                        new
                        {
                            Id = new Guid("5bcbef3c-9790-4032-84c2-3b0706464b6f"),
                            CurrentCapacity = 0,
                            MaxCapacity = 10,
                            Name = "Salle C"
                        },
                        new
                        {
                            Id = new Guid("0f29a8cb-4931-4b60-9473-fd2a3932e2d3"),
                            CurrentCapacity = 0,
                            MaxCapacity = 10,
                            Name = "Salle D"
                        },
                        new
                        {
                            Id = new Guid("7dc3d927-2f26-4c39-bdd2-4b6e17b7d0ac"),
                            CurrentCapacity = 0,
                            MaxCapacity = 5,
                            Name = "Salle E"
                        },
                        new
                        {
                            Id = new Guid("d4fd6f46-7788-4f78-a79a-2f0a5f8c2e7e"),
                            CurrentCapacity = 0,
                            MaxCapacity = 5,
                            Name = "Salle F"
                        },
                        new
                        {
                            Id = new Guid("902beee3-83f5-48c6-8b5b-2214e03bdb20"),
                            CurrentCapacity = 0,
                            MaxCapacity = 50,
                            Name = "Salle G"
                        },
                        new
                        {
                            Id = new Guid("f203c2a4-69b7-43ee-8133-547b1928a99a"),
                            CurrentCapacity = 0,
                            MaxCapacity = 50,
                            Name = "Salle H"
                        },
                        new
                        {
                            Id = new Guid("2aa6be59-5803-4de3-b7f3-9d1f8ef57988"),
                            CurrentCapacity = 0,
                            MaxCapacity = 100,
                            Name = "Salle I"
                        },
                        new
                        {
                            Id = new Guid("7955e403-91e2-4c7b-b9f4-e9f47ce2b850"),
                            CurrentCapacity = 0,
                            MaxCapacity = 100,
                            Name = "Salle J"
                        });
                });

            modelBuilder.Entity("ConfPlan.Shared.Speaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ConferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.ToTable("Speakers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aac7801e-83fc-4f45-89a1-9f867a1efc90"),
                            Bio = "Le professeur Michel Dupont est un expert reconnu en Data Learning, alliant recherche académique et applications industrielles.\nIl enseigne l'intelligence artificielle et le machine learning dans plusieurs établissements de renom.\nSes travaux portent sur l’apprentissage automatique, les réseaux de neurones et les systèmes intelligents.\nIl intervient régulièrement dans des conférences pour partager ses découvertes et pratiques innovantes.\nPassionné par la transmission du savoir, il accompagne aussi des projets en transformation numérique.",
                            Name = "Michel Dupont",
                            PhotoUrl = "https://images.generated.photos/SRoJei2r0zIOyegFdcuLXagsSfVOY-G_WNLiKFIMy-g/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MzMyMzU2LmpwZw.jpg"
                        },
                        new
                        {
                            Id = new Guid("3e499e2f-1db7-4aa9-b3ab-810b5cb7e5b1"),
                            Bio = "Victoria Martin est une spécialiste de l’UI/UX avec plus de 10 ans d’expérience dans la conception centrée utilisateur.\nElle accompagne des entreprises innovantes dans la création d’interfaces intuitives et engageantes.\nSon approche allie design émotionnel, accessibilité et performance.\nElle intervient régulièrement en conférences pour partager sa vision du design éthique et durable.\nVictoria est également mentor pour de jeunes designers qu’elle forme aux meilleures pratiques du secteur.",
                            Name = "Victoria Martin",
                            PhotoUrl = "https://images.generated.photos/BAGgXKAepAIfdaVT-GQ2CMaXys3XZ5qdTVIqL1XFN2E/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/ODE3MTI0LmpwZw.jpg"
                        },
                        new
                        {
                            Id = new Guid("f777e354-cb8c-438c-b15e-5d6ad3eb71e6"),
                            Bio = "Albert MetalStein est un expert visionnaire en physique des métaux et matériaux avancés.\nSes recherches repoussent les limites de la conductivité, de la résistance et de la transformation des alliages.\nIl est reconnu pour ses travaux sur les propriétés quantiques des structures métalliques.\nConférencier passionné, il vulgarise la science du métal avec précision et énergie.\nAlbert collabore avec des laboratoires et industries à la pointe de l’innovation métallurgique.",
                            Name = "Albert MetalStein",
                            PhotoUrl = "https://images.generated.photos/IlHIAAkLdeOdb8dHl4uHy7neqz3DgWD4tE7PcqCGzz4/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/NTMyNzc5LmpwZw.jpg"
                        });
                });

            modelBuilder.Entity("ConfPlan.Shared.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdRole")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57df6d2f-4fbd-49f2-89f2-d3b14a91d6cd"),
                            Email = "admin@confplan.dev",
                            IdRole = new Guid("d5ab69c2-4b14-4a15-8a90-1b3a86eb8aa2"),
                            Password = "$2a$12$ytsbB3JQWKgtrDjAFVJm3eASfxMqBqE8JlYDXBzkPbwt28oFP9unq"
                        });
                });

            modelBuilder.Entity("ConfPlan.Shared.UserConference", b =>
                {
                    b.Property<Guid>("IdUser")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdConference")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("IdUser", "IdConference");

                    b.HasIndex("IdConference");

                    b.ToTable("UserConferences");

                    b.HasData(
                        new
                        {
                            IdUser = new Guid("57df6d2f-4fbd-49f2-89f2-d3b14a91d6cd"),
                            IdConference = new Guid("c21926cc-f0bb-4a65-9ac4-9f4e2ed70530"),
                            Id = new Guid("86a6dfeb-7b9c-4874-9b40-dde63bfc6cf3")
                        },
                        new
                        {
                            IdUser = new Guid("57df6d2f-4fbd-49f2-89f2-d3b14a91d6cd"),
                            IdConference = new Guid("c61f352f-95be-4c41-948a-2cb77a77de1b"),
                            Id = new Guid("fa2c31e3-22f2-4df2-85d1-fcf5b9ae37ae")
                        });
                });

            modelBuilder.Entity("ConfPlan.Shared.Conference", b =>
                {
                    b.HasOne("ConfPlan.Shared.Room", "Room")
                        .WithMany("Conferences")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConfPlan.Shared.Speaker", "Speaker")
                        .WithMany("Conferences")
                        .HasForeignKey("IdSpeaker")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("ConfPlan.Shared.Room", b =>
                {
                    b.HasOne("ConfPlan.Shared.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConfPlan.Shared.Speaker", b =>
                {
                    b.HasOne("ConfPlan.Shared.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId");

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("ConfPlan.Shared.User", b =>
                {
                    b.HasOne("ConfPlan.Shared.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ConfPlan.Shared.UserConference", b =>
                {
                    b.HasOne("ConfPlan.Shared.Conference", "Conference")
                        .WithMany("UserConferences")
                        .HasForeignKey("IdConference")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConfPlan.Shared.User", "User")
                        .WithMany("UserConferences")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conference");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ConfPlan.Shared.Conference", b =>
                {
                    b.Navigation("UserConferences");
                });

            modelBuilder.Entity("ConfPlan.Shared.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ConfPlan.Shared.Room", b =>
                {
                    b.Navigation("Conferences");
                });

            modelBuilder.Entity("ConfPlan.Shared.Speaker", b =>
                {
                    b.Navigation("Conferences");
                });

            modelBuilder.Entity("ConfPlan.Shared.User", b =>
                {
                    b.Navigation("UserConferences");
                });
#pragma warning restore 612, 618
        }
    }
}
